### ISSUE TITLE
Refer to write-up in the repo's README?

### ISSUE THREAD

**Issue by jbrgfx** [aaronrenner/zone-meal-tracker#1]
Your visitors may be unaware that the code is an example of isolating complexity and detailed very nicely in your article "Application Layering . . . ."

https://aaronrenner.io/2019/09/18/application-layering-a-pattern-for-extensible-elixir-application-design.html

Thanks for the write-up.

**Comment by aaronrenner** [comment]
Great idea and thanks so much for the kind feedback! ❤️ 

I just added a link to the readme.
